### PR TITLE
Ft home

### PR DESCRIPTION
**Pull request by DjibrilM**
## In the following pull request I 

- Improve menu CSS and javascript logic

### CODE REVIEW

**Review by mukhammadrizooff — CHANGES_REQUESTED** [review]
Hi @DjibrilM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
- No linter errors ✔️ 
- Correct GitHub Flow ✔️ 
- Good implementations ✔️ 
- Descriptive `README` file ✔️ 

## Required Changes ♻️

- [ ] [REQUIRED] [`README`] Good job so far! The `README` should contains an "Acknowledgements" section, similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/) 👍🏼 

image

#

- [ ] [REQUIRED] [`HOME PAGE`] Good job so far! Please add all `elements`(social icons and cc compaign) to your `frst` and `second` navigation menues  like a [Behance Design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)🙏🏼  

image

#

- [ ] [REQUIRED] [`HOME PAGE`] Good job so far! Please give correct `design` with correct `compostiion`(e.g color, text, picture...) to `home` page 🙏🏼 

image

#

- [ ] [REQUIRED] [`HOME PAGE`] Good job so far! Please add `one` card(There should have `5`) and give correct `hover` effect to each card like a [Behance design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) 🙏🏼


image

#

- [ ] [REQUIRED] [`HOME PAGE`] Good job so far! Please add orange horizontal line under the text of `Our Experts` and give the correct `size` to `gray horizontal line`  🙏🏼 

image

#

- [ ] [REQUIRED] [`ABOUT PAGE`] Good job so far! Please implement the `center` to `horizontal line` under the `Text` of `See the past Exhibitions` and remove the necessary `horizontal` lines from `exhibition` cards 🙏🏼 

image

#

- [ ] [REQUIRED] [`ABOUT PAGE`] Good job so far! Please add the `horizontal` line to required part mentioned  below the picture 🙏🏼  

image

#

- [ ] [REQUIRED] [`HOME & ABOUT PAGE`] Good job so far! Please give correct postion and font size to `texts` placed on `footer` section 🙏🏼 

image

#

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DjibrilM** [comment]
I think as required for this project we are not limited to only the provided design but we can modify it and add thing like colors and images.

The only thing that we have to respect is the structure of the design

**Comment by DjibrilM** [comment]
> Hi @DjibrilM,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
>  [ 68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966 ](https://camo.githubusercontent.com/7e9210dcfdfd707fee9896010cd3908fb63e8afc568301ba1c1d5cba19e1499f/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966) [ ](https://camo.githubusercontent.com/7e9210dcfdfd707fee9896010cd3908fb63e8afc568301ba1c1d5cba19e1499f/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)
> 
> ## Highlights
> * No linter errors heavy_check_mark
> * Correct GitHub Flow heavy_check_mark
> * Good implementations heavy_check_mark
> * Descriptive `README` file heavy_check_mark
> 
> ## Required Changes 
> * [ ]  [REQUIRED] [`README`] Good job so far! The `README` should contains an "Acknowledgements" section, similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/)
> 
> image
> 
> * [ ]  [REQUIRED] [`HOME PAGE`] Good job so far! Please add all `elements`(social icons and cc compaign) to your `frst` and `second` navigation menues  like a [Behance Design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)
> 
> image
> 
> * [ ]  [REQUIRED] [`HOME PAGE`] Good job so far! Please give correct `design` with correct `compostiion`(e.g color, text, picture...) to `home` page
> 
> image
> 
> * [ ]  [REQUIRED] [`HOME PAGE`] Good job so far! Please add `one` card(There should have `5`) and give correct `hover` effect to each card like a [Behance design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)
> 
> image
> 
> * [ ]  [REQUIRED] [`HOME PAGE`] Good job so far! Please add orange horizontal line under the text of `Our Experts` and give the correct `size` to `gray horizontal line`
> 
> image
> 
> * [ ]  [REQUIRED] [`ABOUT PAGE`] Good job so far! Please implement the `center` to `horizontal line` under the `Text` of `See the past Exhibitions` and remove the necessary `horizontal` lines from `exhibition` cards
> 
> image
> 
> * [ ]  [REQUIRED] [`ABOUT PAGE`] Good job so far! Please add the `horizontal` line to required part mentioned  below the picture
> 
> image
> 
> * [ ]  [REQUIRED] [`HOME & ABOUT PAGE`] Good job so far! Please give correct postion and font size to `texts` placed on `footer` section
> 
> image
> 
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mukhammadrizooff** [comment]
> I think as required for this project we are not limited to only the provided design but we can modify it and add thing like colors and images.
> 
> The only thing that we have to respect is the structure of the design

# @DjibrilM Yeah you right only for Content(e.g Comapny name and text materials) not a composition(e.g layout, color, space identations and assets) 👍🏼

**Pull request merged**
